version: '3.3'
services:
  plantel:
    container_name: plantel
    build:
      context: ./plantel/
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - './plantel/:/var/www/html/'
    ports:
      - '8001:80'
  db:
    container_name: db
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3303:3306'

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8083:80'
    volumes:
      - './phpmyadmin/uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini' 